{"stats": {"errors": 0, "failures": 1, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:TestVariables", "name": "test_travel_month", "time": 0.00046443939208984375, "type": "failure", "errtype": "builtins.AssertionError", "message": "None != 'January'", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 67, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 625, in run\n    testMethod()\n  File \"/home/yoyothesheep/python-variables-lab-data-science/test/index_test.py\", line 6, in test_travel_month\n    self.assertEqual(travel_month, 'January')\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 836, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 829, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: None != 'January'\n"}]}